{"name": "Переход в раздел \"История заказов\"", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16", "trace": "self = <tests.test_lk.TestLk object at 0x0000026DBE1CBD70>, driver = <selenium.webdriver.firefox.webdriver.WebDriver (session=\"516a7dd1-ec9f-4a36-8013-17dff11a414d\")>\n\n    @allure.title('Переход в раздел \"История заказов\"')\n    def test_go_to_feed_orders(self, driver):\n        login = LoginPage(driver)\n>       login.login(\"gismo513@mail.ru\", \"123456789\")\n\ntests\\test_lk.py:20: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages\\login_page.py:26: in login\n    self.input_email(email)\npages\\login_page.py:10: in input_email\n    self.set_text_to_elemet(LogLocators.EMAIL_INPUT, email)\npages\\base_page.py:33: in set_text_to_elemet\n    element = self.find_element_with_wait(locator)\npages\\base_page.py:18: in find_element_with_wait\n    WebDriverWait(self.driver, 15).until(EC.visibility_of_element_located(locator))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"516a7dd1-ec9f-4a36-8013-17dff11a414d\")>, method = <function visibility_of_element_located.<locals>._predicate at 0x0000026DBE287F60>, message = ''\n\n    def until(self, method: Callable[[D], Union[Literal[False], T]], message: str = \"\") -> T:\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nE       WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nE       NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5\nE       dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py:105: TimeoutException"}, "steps": [{"name": "Ввод email", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\n", "trace": "  File \"C:\\Users\\Home PC\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\Home PC\\Desktop\\Auto QA\\Diplom\\Diplom_3.0.0\\pages\\login_page.py\", line 10, in input_email\n    self.set_text_to_elemet(LogLocators.EMAIL_INPUT, email)\n  File \"C:\\Users\\Home PC\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\Home PC\\Desktop\\Auto QA\\Diplom\\Diplom_3.0.0\\pages\\base_page.py\", line 33, in set_text_to_elemet\n    element = self.find_element_with_wait(locator)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Home PC\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\Home PC\\Desktop\\Auto QA\\Diplom\\Diplom_3.0.0\\pages\\base_page.py\", line 18, in find_element_with_wait\n    WebDriverWait(self.driver, 15).until(EC.visibility_of_element_located(locator))\n  File \"C:\\Users\\Home PC\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 105, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "steps": [{"name": "Установить текст", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\n", "trace": "  File \"C:\\Users\\Home PC\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\Home PC\\Desktop\\Auto QA\\Diplom\\Diplom_3.0.0\\pages\\base_page.py\", line 33, in set_text_to_elemet\n    element = self.find_element_with_wait(locator)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Home PC\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\Home PC\\Desktop\\Auto QA\\Diplom\\Diplom_3.0.0\\pages\\base_page.py\", line 18, in find_element_with_wait\n    WebDriverWait(self.driver, 15).until(EC.visibility_of_element_located(locator))\n  File \"C:\\Users\\Home PC\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 105, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "steps": [{"name": "Найти элемент с ожиданием", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\n", "trace": "  File \"C:\\Users\\Home PC\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\Home PC\\Desktop\\Auto QA\\Diplom\\Diplom_3.0.0\\pages\\base_page.py\", line 18, in find_element_with_wait\n    WebDriverWait(self.driver, 15).until(EC.visibility_of_element_located(locator))\n  File \"C:\\Users\\Home PC\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 105, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "parameters": [{"name": "locator", "value": "['name', 'name']"}], "start": 1730055789657, "stop": 1730055804789}], "parameters": [{"name": "locator", "value": "['name', 'name']"}, {"name": "text", "value": "'gismo513@mail.ru'"}], "start": 1730055789657, "stop": 1730055804789}], "parameters": [{"name": "email", "value": "'gismo513@mail.ru'"}], "start": 1730055789657, "stop": 1730055804789}], "parameters": [{"name": "driver", "value": "'firefox'"}], "start": 1730055789657, "stop": 1730055804789, "uuid": "8f8a10f2-fb3d-432c-bdb9-5b4dc54fea4c", "historyId": "b61851031f1b1abb75bdb4ebdf5da514", "testCaseId": "3c20173be2f320acdfd1906d324df06c", "fullName": "tests.test_lk.TestLk#test_go_to_feed_orders", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_lk"}, {"name": "subSuite", "value": "TestLk"}, {"name": "host", "value": "DESKTOP-TS1EIDP"}, {"name": "thread", "value": "9664-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_lk"}]}